### ISSUE TITLE
time synchronization

### ISSUE THREAD

**Issue by pgawlowicz** [wishful-project/final_showcase#1]
If i understand correctly you are trying to synchronize time among nodes here. Wouldn't be it easier to use simply NTP or PTP protocols?

https://github.com/wishful-project/final_showcase/blob/6d5322088f900a7a7b76b26275a6eb18cccce4b9/solution_interference_detection/helper/sync_date.sh#L9-L12

**Comment by mchwalisz** [comment]
I agree that even [NTP](https://help.ubuntu.com/lts/serverguide/NTP.html) will give better results. 

It should be easy to use it with `systemd`.

```
sudo systemctl status ntp.service
sudo systemctl enable --now ntp.service
```

**Comment by domenico-garlisi** [comment]
Yes, I am completely agree with you, this was only a quick and dirty implementation, I will change it in the next push.
